### ISSUE TITLE
Unclear usage

### ISSUE THREAD

**Issue by josephrexme** [SUKOHI/PiecewiseDistortion#1]
What is `pil_im`? where is it defined? where do you apply the image referenced through file_path?

**Comment by SUKOHI** [comment]
Hi, josephrexme.
Thank you for the message.

`pil_im` means pillow(PIL) image resource.
So I suppose you can load an image like the bellow.

from PIL import Image
pil_im = Image.open('your-image.jpg')

or [more](http://pillow.readthedocs.io/en/5.2.x/reference/Image.html#examples).

**Comment by josephrexme** [comment]
Thanks!
